export const GOOGLE_CITY_MAP: Record<string, string> = {
  'mumbai': 'Mumbai',
  'navi mumbai': 'Mumbai',
  'thane': 'Mumbai',
  'dombivli': 'Mumbai',
  'kalyan': 'Mumbai',
  'vasai-virar': 'Mumbai',
  'virar': 'Mumbai',
  'mira bhayandar': 'Mumbai',
  'bhiwandi': 'Mumbai',
  'ambernath': 'Mumbai',
  'nala sopara': 'Mumbai',
  'palghar': 'Mumbai',
  'panvel': 'Mumbai',
  'vasai': 'Mumbai',
  'vashi': 'Mumbai',
  'ghansoli': 'Mumbai',
  'sanpada': 'Mumbai',
  'mahape': 'Mumbai',
  'malad east': 'Mumbai',
  'kandivali east': 'Mumbai',
  'mira road east': 'Mumbai',
  'seawoods': 'Mumbai',
  'worli': 'Mumbai',
  'ulhasnagar': 'Mumbai',
  'virar east': 'Mumbai',
  'mulund west': 'Mumbai',
  'bhandup west': 'Mumbai',
  'bhayandar east': 'Mumbai',
  'cbd belapur': 'Mumbai',
  'rabale': 'Mumbai',
  'mazgaon': 'Mumbai',
  'bandra west': 'Mumbai',
  'byculla': 'Mumbai',
  'juhu': 'Mumbai',
  'dahisar west': 'Mumbai',
  'parel': 'Mumbai',
  'khadakpada': 'Mumbai',
  'fort': 'Mumbai',
  'jogeshwari east': 'Mumbai',
  'hyderabad': 'Hyderabad',
  'secunderabad': 'Hyderabad',
  'sangareddy': 'Hyderabad',
  'serilingampalli': 'Hyderabad',
  'malkajgiri': 'Hyderabad',
  'balanagar': 'Hyderabad',
  'patan cheruvu': 'Hyderabad',
  'qutubullapur': 'Hyderabad',
  'saroornagar': 'Hyderabad',
  'nizampet': 'Hyderabad',
  'jubilee hills': 'Hyderabad',
  'alwal': 'Hyderabad',
  'banjara hills': 'Hyderabad',
  'khairtabad': 'Hyderabad',
  'cherlapalli': 'Hyderabad',
  'bachupally': 'Hyderabad',
  'manchirevula': 'Hyderabad',
  'bolarum': 'Hyderabad',
  'jagathgiri gutta': 'Hyderabad',
  'hastinapuram': 'Hyderabad',
  'nizamabad, telangana': 'Hyderabad',
  'chennai': 'Chennai',
  'shollinganallur': 'Chennai',
  'mylapore': 'Chennai',
  'aminjikarai': 'Chennai',
  'tambaram': 'Chennai',
  'pallavaram': 'Chennai',
  'egmore': 'Chennai',
  'kanchipuram': 'Chennai',
  'thiruvallur': 'Chennai',
  'velachery': 'Chennai',
  'madipakkam': 'Chennai',
  'medavakkam': 'Chennai',
  'tharamani': 'Chennai',
  'manapakkam': 'Chennai',
  'sholinganallur': 'Chennai',
  'meenambakkam': 'Chennai',
  'nungambakkam': 'Chennai',
  'pammal': 'Chennai',
  'kodungaiyur': 'Chennai',
  'kovilambakkam': 'Chennai',
  'thiruverkadu': 'Chennai',
  'injambakkam': 'Chennai',
  'korattur': 'Chennai',
  'madambakkam': 'Chennai',
  'george town': 'Chennai',
  'bengaluru': 'Bengaluru',
  'bangalore': 'Bengaluru',
  'mahadevapura': 'Bengaluru',
  'jayanagar': 'Bengaluru',
  'brookefield': 'Bengaluru',
  'krishnarajapura': 'Bengaluru',
  'krishnarajapuram': 'Bengaluru',
  'c v raman nagar': 'Bengaluru',
  'koramangala': 'Bengaluru',
  'balagere': 'Bengaluru',
  'indirapuram': 'Ghaziabad',
  'rajajinagar': 'Bengaluru',
  'nayanda halli': 'Bengaluru',
  'rayasandra': 'Bengaluru',
  'bellandur': 'Bengaluru',
  'akshayanagar': 'Bengaluru',
  'chikkakannalli': 'Bengaluru',
  'indiranagar': 'Bengaluru',
  'subramanyapura': 'Bengaluru',
  'narayanapura': 'Bengaluru',
  'kudlu': 'Bengaluru',
  'new delhi': 'Delhi',
  'delhi': 'Delhi',
  'civil lines': 'Delhi',
  'punjabi bagh': 'Delhi',
  'kalkaji': 'Delhi',
  'saket': 'Delhi',
  'defence colony': 'Delhi',
  'saraswati vihar': 'Delhi',
  'mayur vihar': 'Delhi',
  'dwarka': 'Delhi',
  'rajouri garden': 'Delhi',
  'preet vihar': 'Delhi',
  'hauz khas': 'Delhi',
  'vasant vihar': 'Delhi',
  'vasant kunj': 'Delhi',
  'lajpat nagar': 'Delhi',
  'badarpur': 'Delhi',
  'ashok vihar': 'Delhi',
  'rama krishna puram': 'Delhi',
  'mukherjee nagar': 'Delhi',
  'mehrauli': 'Delhi',
  'malviya nagar': 'Delhi',
  'shalimar bagh': 'Delhi',
  'yamuna bank': 'Delhi',
  'shankar vihar': 'Delhi',
  'dilshad garden': 'Delhi',
  'greater kailash': 'Delhi',
  'pune': 'Pune',
  'pimpri-chinchwad': 'Pune',
  'haveli': 'Pune',
  'pimpri colony': 'Pune',
  'nigdi': 'Pune',
  'chinchwad': 'Pune',
  'ravet': 'Pune',
  'pimple nilakh': 'Pune',
  'wagholi': 'Pune',
  'wakad': 'Pune',
  'kondhwa': 'Pune',
  'mundhwa': 'Pune',
  'viman nagar': 'Pune',
  'ghorpadi': 'Pune',
  'wanowrie': 'Pune',
  'wadgaon sheri': 'Pune',
  'yerawada': 'Pune',
  'dhanori': 'Pune',
  'akurdi': 'Pune',
  'noida': 'Noida',
  'greater noida': 'Noida',
  'dadri': 'Noida',
  'amrapali leisure valley': 'Noida',
  'amrapali dream valley': 'Noida',
  'sector 62': 'Noida',
  'sector 62a': 'Noida',
  'sector 18': 'Noida',
  'sector 50 noida': 'Noida',
  'sector 51 noida': 'Noida',
  'sector 75 noida': 'Noida',
  'sector 76 noida': 'Noida',
  'sector 78 noida': 'Noida',
  'sector 100 noida': 'Noida',
  'sector 110 noida': 'Noida',
  'sector 121 noida': 'Noida',
  'sector 137 noida': 'Noida',
  'sector 143 noida': 'Noida',
  'sector 150 noida': 'Noida',
  'sector 168 noida': 'Noida',
  'bisrakh': 'Noida',
  'jewar': 'Noida',
  'surajpur': 'Noida',
  'noida extension': 'Noida',
  'knowledge park': 'Noida',
  'techzone': 'Noida',
  'ahmedabad': 'Ahmedabad',
  'ahmadabad': 'Ahmedabad',
  'bodakdev': 'Ahmedabad',
  'bopal': 'Ahmedabad',
  'paldi': 'Ahmedabad',
  'maninagar': 'Ahmedabad',
  'nikol': 'Ahmedabad',
  'kolkata': 'Kolkata',
  'howrah': 'Kolkata',
  'tangra': 'Kolkata',
  'lucknow': 'Lucknow',
  'gurgaon': 'Gurgaon',
  'gurugram': 'Gurgaon',
  'sector 54': 'Gurgaon',
  'dlf city phase 1': 'Gurgaon',
  'dlf city phase 2': 'Gurgaon',
  'dlf city phase 3': 'Gurgaon',
  'dlf city phase 4': 'Gurgaon',
  'dlf city phase 5': 'Gurgaon',
  'sohna': 'Gurgaon',
  'manesar': 'Gurgaon',
  'palam vihar': 'Gurgaon',
  'udyog vihar': 'Gurgaon',
  'cyber city': 'Gurgaon',
  'golf course road': 'Gurgaon',
  'nirvana country': 'Gurgaon',
  'ardee city': 'Gurgaon',
  'south city 1': 'Gurgaon',
  'south city 2': 'Gurgaon',
  'huda city centre': 'Gurgaon',
  'mg road gurugram': 'Gurgaon',
  'sector 14 gurugram': 'Gurgaon',
  'sector 15 gurugram': 'Gurgaon',
  'sector 17 gurugram': 'Gurgaon',
  'sector 23 gurugram': 'Gurgaon',
  'sector 29 gurugram': 'Gurgaon',
  'sector 31 gurugram': 'Gurgaon',
  'sector 40 gurugram': 'Gurgaon',
  'sector 43 gurugram': 'Gurgaon',
  'sector 45 gurugram': 'Gurgaon',
  'sector 46 gurugram': 'Gurgaon',
  'sector 47 gurugram': 'Gurgaon',
  'sector 56 gurugram': 'Gurgaon',
  'sector 57 gurugram': 'Gurgaon',
  'sector 65 gurugram': 'Gurgaon',
  'sector 67 gurugram': 'Gurgaon',
  'sector 82 gurugram': 'Gurgaon',
  'sector 83 gurugram': 'Gurgaon',
  'wazirabad gurugram': 'Gurgaon',
  'sheetla mata road': 'Gurgaon',
  'badshahpur': 'Gurgaon',
  'bhondsi': 'Gurgaon',
  'bhubaneswar': 'Bhubaneswar',
  'khordha': 'Bhubaneswar',
  'karimganj': 'Bhubaneswar',
  'jajapur': 'Bhubaneswar',
  'jajpur': 'Bhubaneswar',
  'bargarh': 'Bhubaneswar',
  'bhubaneshwar': 'Bhubaneswar',
  'nayapalli': 'Bhubaneswar',
  'cuttack': 'Bhubaneswar',
  'puri': 'Bhubaneswar',
  'patia': 'Bhubaneswar',
  'chandrasekharpur': 'Bhubaneswar',
  'saheed nagar': 'Bhubaneswar',
  'rasulgarh': 'Bhubaneswar',
  'mancheswar': 'Bhubaneswar',
  'IRC village': 'Bhubaneswar',
  'jaydev vihar': 'Bhubaneswar',
  'damana': 'Bhubaneswar',
  'baramunda': 'Bhubaneswar',
  'aiginia': 'Bhubaneswar',
  'sambalpur': 'Bhubaneswar',
  'berhampur': 'Bhubaneswar',
  'balasore': 'Bhubaneswar',
  'rourkela': 'Bhubaneswar',
  'surat': 'Surat',
  'athwa': 'Surat',
  'indore': 'Indore',
  'jaipur': 'Jaipur',
  'vijay nagar indore': 'Indore',
  'palasia': 'Indore',
  'rajendra nagar indore': 'Indore',
  'scheme 54': 'Indore',
  'scheme 78': 'Indore',
  'bhawarkuan': 'Indore',
  'nipania': 'Indore',
  'lasudia mori': 'Indore',
  'super corridor': 'Indore',
  'rau': 'Indore',
  'pithampur': 'Indore',
  'mhow': 'Indore',
  'dewas': 'Indore',
  'sanwer': 'Indore',
  'sanganer': 'Jaipur',
  'mansarovar': 'Jaipur',
  'vaishali nagar jaipur': 'Jaipur',
  'malviya nagar jaipur': 'Jaipur',
  'tonk road': 'Jaipur',
  'ajmer road': 'Jaipur',
  'sirsi road': 'Jaipur',
  'jagatpura': 'Jaipur',
  'muhana': 'Jaipur',
  'pratap nagar jaipur': 'Jaipur',
  'sitapura': 'Jaipur',
  'bagru': 'Jaipur',
  'amber': 'Jaipur',
  'amer': 'Jaipur',
  'kalwar': 'Jaipur',
  'chomu': 'Jaipur',
  'visakhapatnam': 'Visakhapatnam',
  'vijayawada': 'Vijayawada',
  'vizag': 'Visakhapatnam',
  'gajuwaka': 'Visakhapatnam',
  'mvp colony': 'Visakhapatnam',
  'seethammadhara': 'Visakhapatnam',
  'rushikonda': 'Visakhapatnam',
  'madhurawada': 'Visakhapatnam',
  'kommadi': 'Visakhapatnam',
  'pendurthi': 'Visakhapatnam',
  'bheemunipatnam': 'Visakhapatnam',
  'anakapalle': 'Visakhapatnam',
  'bheemili': 'Visakhapatnam',
  'gopalapatnam': 'Visakhapatnam',
  'guntur': 'Guntur',
  'thiruvananthapuram': 'Thiruvananthapuram',
  'guwahati': 'Guwahati',
  'vadodara': 'Vadodara',
  'ludhiana': 'Ludhiana',
  'rajkot': 'Rajkot',
  'bhakti nagar': 'Rajkot',
  'nashik': 'Nashik',
  'faridabad': 'Faridabad',
  'ballabhgarh': 'Faridabad',
  'old faridabad': 'Faridabad',
  'nit faridabad': 'Faridabad',
  'sector 16 faridabad': 'Faridabad',
  'sector 17 faridabad': 'Faridabad',
  'sector 21 faridabad': 'Faridabad',
  'sector 28 faridabad': 'Faridabad',
  'sector 29 faridabad': 'Faridabad',
  'neharpar': 'Faridabad',
  'greater faridabad': 'Faridabad',
  'mujesar': 'Faridabad',
  'tigaon': 'Faridabad',
  'mangalore': 'Mangaluru',
  'mangaluru': 'Mangaluru',
  'ghaziabad': 'Ghaziabad',
  'pratap vihar': 'Ghaziabad',
  'vaishali': 'Ghaziabad',
  'kaushambi': 'Ghaziabad',
  'raj nagar extension': 'Ghaziabad',
  'crossings republik': 'Ghaziabad',
  'mohan nagar': 'Ghaziabad',
  'vasundhara': 'Ghaziabad',
  'rajendra nagar ghaziabad': 'Ghaziabad',
  'sanjay nagar ghaziabad': 'Ghaziabad',
  'govindpuram': 'Ghaziabad',
  'dundahera': 'Ghaziabad',
  'loni': 'Ghaziabad',
  'tronica city': 'Ghaziabad',
  'sahibabad': 'Ghaziabad',
  'hindon': 'Ghaziabad',
  'warangal': 'Warangal',
  'kochi': 'Kochi',
  'edappal': 'Kochi',
  'ernakulam': 'Kochi',
  'kanayannur': 'Kochi',
  'elamakkara': 'Kochi',
  'coimbatore': 'Coimbatore',
  'saravanampatti': 'Coimbatore',
  'mysuru': 'Mysore',
  'mysore': 'Mysore',
  'nagpur': 'Nagpur',
  'panaji': 'Goa',
  'old goa': 'Goa',
  'mohali': 'Mohali',
  'sahibzada ajit singh nagar': 'Mohali',
  'chandigarh': 'Chandigarh',
  'patna': 'Patna',
  'dehradun': 'Dehradun',
  'thrissur': 'Thrissur',
  'hubballi': 'Hubballi',
  'salem': 'Salem',
  'chhatrapati sambhajinagar': 'Sambhaji Nagar',
  'aurangabad': 'Sambhaji Nagar',
  'sambhaji nagar': 'Sambhaji Nagar',
  'belgaum': 'Belgaum',
  'belagavi': 'Belgaum',
  'kakinada': 'Kakinada',
  'bhopal': 'Bhopal',
  'kolhapur': 'Kolhapur',
  'kozhikode': 'Kozhikode',
  'madurai': 'Madurai',
  'kanpur': 'Kanpur',
  'tiruchirappalli': 'Tiruchirappalli',
  'kota': 'Kota',
  'tiruppur': 'Tiruppur',
  'tirupati': 'Tirupati',
  'rajahmundry': 'Rajahmundry',
  'rajamahendravaram': 'Rajahmundry',
  'udaipur': 'Udaipur',
  'sangli': 'Sangli',
  'karimnagar': 'KarimNagar',
  'bellari': 'Ballari',
  'ballari': 'Ballari',
  'hosur': 'Hosur',
  'atal nagar-nava raipur': 'Raipur',
  'raipur': 'Raipur',
  'salt lake city': 'Kolkata',
  'bidhannagar': 'Kolkata',
  'dum dum': 'Kolkata',
  'barasat': 'Kolkata',
  'barrackpore': 'Kolkata',
  'madhyamgram': 'Kolkata',
  'rajarhat': 'Kolkata',
  'new town kolkata': 'Kolkata',
  'garia': 'Kolkata',
  'jadavpur': 'Kolkata',
  'behala': 'Kolkata',
  'tollygunge': 'Kolkata',
  'ballygunge': 'Kolkata',
  'alipore': 'Kolkata',
  'serampore': 'Kolkata',
  'uttarpara': 'Kolkata',
  'bally': 'Kolkata',
  'uluberia': 'Kolkata',
  'gomti nagar': 'Lucknow',
  'hazratganj': 'Lucknow',
  'alambagh': 'Lucknow',
  'aliganj lucknow': 'Lucknow',
  'indira nagar lucknow': 'Lucknow',
  'mahanagar lucknow': 'Lucknow',
  'vikas nagar lucknow': 'Lucknow',
  'rajajipuram': 'Lucknow',
  'chinhat': 'Lucknow',
  'faizabad road': 'Lucknow',
  'kanpur road lucknow': 'Lucknow',
  'kursi road': 'Lucknow',
  'jhotwara': 'Jaipur',
  'murlipura': 'Jaipur',
  'vidhyadhar nagar': 'Jaipur',
  'sodala': 'Jaipur',
  'durgapura': 'Jaipur',
  'raja park': 'Jaipur',
  'c scheme': 'Jaipur',
  'bani park': 'Jaipur',
  'gopalpura': 'Jaipur',
  'khajrana': 'Indore',
  'kanadiya': 'Indore',
  'pardeshipura': 'Indore',
  'aerodrome road': 'Indore',
  'dwaraka nagar': 'Visakhapatnam',
  'ukkunagaram': 'Visakhapatnam',
  'simhachalam': 'Visakhapatnam',
  'yendada': 'Visakhapatnam',
  'vizianagaram': 'Visakhapatnam',
  'srikakulam': 'Visakhapatnam',
  'zirakpur': 'Chandigarh',
  'derabassi': 'Chandigarh',
  'kharar': 'Chandigarh',
  'mullanpur': 'Chandigarh',
  'trivandrum': 'Thiruvananthapuram',
  'kazhakkoottam': 'Thiruvananthapuram',
  'peroorkada': 'Thiruvananthapuram',
  'sreekaryam': 'Thiruvananthapuram',
  'neyyattinkara': 'Thiruvananthapuram',
  'attingal': 'Thiruvananthapuram',
  'vattiyoorkavu': 'Thiruvananthapuram',
  'peelamedu': 'Coimbatore',
  'singanallur': 'Coimbatore',
  'ganapathy': 'Coimbatore',
  'podanur': 'Coimbatore',
  'vadavalli': 'Coimbatore',
  'sulur': 'Coimbatore',
  'mettupalayam': 'Coimbatore',
  'rs puram': 'Coimbatore',
  'trichy': 'Tiruchirappalli',
  'tiruchi': 'Tiruchirappalli',
  'tiruchirapalli': 'Tiruchirappalli',
  'srirangam': 'Tiruchirappalli',
  'woraiyur': 'Tiruchirappalli',
  'thillai nagar': 'Tiruchirappalli',
  'narsampet': 'Warangal',
  'parkal': 'Warangal',
  'mahabubabad': 'Warangal',
  'kondapur': 'Hyderabad',
  'nallagandla': 'Hyderabad',
  'adai': 'Mumbai',
  'kelambakkam': 'Chennai',
  'guduvancheri': 'Chennai',
  'kakkanad': 'Kochi',
  'new town': 'Kolkata',
  'madgaon': 'Goa',
};

export const TSC_CITIES = [
  'Bengaluru', 'Hyderabad', 'Mumbai', 'Rest', 'Chennai', 'Delhi',
  'Pune', 'Noida', 'Ahmedabad', 'Kolkata', 'Lucknow', 'Gurgaon',
  'Indore', 'Jaipur', 'Kochi', 'Coimbatore', 'Bhubaneswar', 'Surat',
  'Visakhapatnam', 'Vijayawada', 'Guwahati', 'Thiruvananthapuram',
  'Guntur', 'Vadodara', 'Faridabad', 'Ghaziabad', 'Ludhiana',
  'Mangaluru', 'Warangal', 'Rajkot', 'Nashik', 'Mysore', 'Goa',
  'Mohali', 'Nagpur', 'Dehradun', 'Patna', 'Thrissur', 'Kozhikode',
  'Madurai', 'Hubballi', 'Salem', 'Sambhaji Nagar', 'Kanpur',
  'Tiruchirappalli', 'Belgaum', 'Kakinada', 'Kolhapur', 'Bhopal',
  'Kota', 'Tiruppur', 'Tirupati', 'Rajahmundry', 'Udaipur', 'Sangli',
  'KarimNagar', 'Ballari', 'Hosur', 'Chandigarh', 'Raipur',
  'Unknown',
];

export function mapGoogleCity(googleCityName: string): string {
  if (!googleCityName || googleCityName.trim() === '') return 'Unknown';
  const lower = googleCityName.toLowerCase().trim();
  return GOOGLE_CITY_MAP[lower] || 'Rest';
}
