export const GOOGLE_CITY_MAP: Record<string, string> = {
  'mumbai': 'Mumbai',
  'navi mumbai': 'Mumbai',
  'thane': 'Mumbai',
  'dombivli': 'Mumbai',
  'kalyan': 'Mumbai',
  'vasai-virar': 'Mumbai',
  'virar': 'Mumbai',
  'mira bhayandar': 'Mumbai',
  'bhiwandi': 'Mumbai',
  'ambernath': 'Mumbai',
  'nala sopara': 'Mumbai',
  'palghar': 'Mumbai',
  'panvel': 'Mumbai',
  'vasai': 'Mumbai',
  'vashi': 'Mumbai',
  'ghansoli': 'Mumbai',
  'sanpada': 'Mumbai',
  'mahape': 'Mumbai',
  'malad east': 'Mumbai',
  'kandivali east': 'Mumbai',
  'mira road east': 'Mumbai',
  'seawoods': 'Mumbai',
  'worli': 'Mumbai',
  'ulhasnagar': 'Mumbai',
  'mulund west': 'Mumbai',
  'bhandup west': 'Mumbai',
  'virar east': 'Mumbai',
  'fort': 'Mumbai',
  'jogeshwari east': 'Mumbai',
  'bhayandar east': 'Mumbai',
  'cbd belapur': 'Mumbai',
  'rabale': 'Mumbai',
  'mazgaon': 'Mumbai',
  'bandra west': 'Mumbai',
  'byculla': 'Mumbai',
  'juhu': 'Mumbai',
  'dahisar west': 'Mumbai',
  'parel': 'Mumbai',
  'khadakpada': 'Mumbai',
  'hyderabad': 'Hyderabad',
  'secunderabad': 'Hyderabad',
  'sangareddy': 'Hyderabad',
  'serilingampalli': 'Hyderabad',
  'malkajgiri': 'Hyderabad',
  'balanagar': 'Hyderabad',
  'patan cheruvu': 'Hyderabad',
  'qutubullapur': 'Hyderabad',
  'saroornagar': 'Hyderabad',
  'nizampet': 'Hyderabad',
  'jubilee hills': 'Hyderabad',
  'alwal': 'Hyderabad',
  'banjara hills': 'Hyderabad',
  'khairtabad': 'Hyderabad',
  'cherlapalli': 'Hyderabad',
  'bachupally': 'Hyderabad',
  'manchirevula': 'Hyderabad',
  'bolarum': 'Hyderabad',
  'jagathgiri gutta': 'Hyderabad',
  'hastinapuram': 'Hyderabad',
  'nizamabad, telangana': 'Hyderabad',
  'chennai': 'Chennai',
  'shollinganallur': 'Chennai',
  'mylapore': 'Chennai',
  'aminjikarai': 'Chennai',
  'tambaram': 'Chennai',
  'pallavaram': 'Chennai',
  'egmore': 'Chennai',
  'kanchipuram': 'Chennai',
  'thiruvallur': 'Chennai',
  'velachery': 'Chennai',
  'tharamani': 'Chennai',
  'madipakkam': 'Chennai',
  'medavakkam': 'Chennai',
  'sholinganallur': 'Chennai',
  'manapakkam': 'Chennai',
  'george town': 'Chennai',
  'meenambakkam': 'Chennai',
  'madambakkam': 'Chennai',
  'nungambakkam': 'Chennai',
  'pammal': 'Chennai',
  'kodungaiyur': 'Chennai',
  'kovilambakkam': 'Chennai',
  'thiruverkadu': 'Chennai',
  'injambakkam': 'Chennai',
  'korattur': 'Chennai',
  'bengaluru': 'Bengaluru',
  'mahadevapura': 'Bengaluru',
  'jayanagar': 'Bengaluru',
  'brookefield': 'Bengaluru',
  'krishnarajapura': 'Bengaluru',
  'c v raman nagar': 'Bengaluru',
  'koramangala': 'Bengaluru',
  'balagere': 'Bengaluru',
  'indirapuram': 'Bengaluru',
  'rajajinagar': 'Bengaluru',
  'bellandur': 'Bengaluru',
  'nayanda halli': 'Bengaluru',
  'rayasandra': 'Bengaluru',
  'krishnarajapuram': 'Bengaluru',
  'indiranagar': 'Bengaluru',
  'subramanyapura': 'Bengaluru',
  'narayanapura': 'Bengaluru',
  'kudlu': 'Bengaluru',
  'akshayanagar': 'Bengaluru',
  'chikkakannalli': 'Bengaluru',
  'new delhi': 'Delhi',
  'delhi': 'Delhi',
  'civil lines': 'Delhi',
  'punjabi bagh': 'Delhi',
  'kalkaji': 'Delhi',
  'saket': 'Delhi',
  'defence colony': 'Delhi',
  'saraswati vihar': 'Delhi',
  'mayur vihar': 'Delhi',
  'dwarka': 'Delhi',
  'rajouri garden': 'Delhi',
  'preet vihar': 'Delhi',
  'hauz khas': 'Delhi',
  'vasant vihar': 'Delhi',
  'vasant kunj': 'Delhi',
  'lajpat nagar': 'Delhi',
  'greater kailash': 'Delhi',
  'badarpur': 'Delhi',
  'ashok vihar': 'Delhi',
  'rama krishna puram': 'Delhi',
  'mukherjee nagar': 'Delhi',
  'mehrauli': 'Delhi',
  'malviya nagar': 'Delhi',
  'shalimar bagh': 'Delhi',
  'yamuna bank': 'Delhi',
  'shankar vihar': 'Delhi',
  'dilshad garden': 'Delhi',
  'pune': 'Pune',
  'pimpri-chinchwad': 'Pune',
  'haveli': 'Pune',
  'pimpri colony': 'Pune',
  'nigdi': 'Pune',
  'chinchwad': 'Pune',
  'ravet': 'Pune',
  'wakad': 'Pune',
  'wagholi': 'Pune',
  'pimple nilakh': 'Pune',
  'kondhwa': 'Pune',
  'mundhwa': 'Pune',
  'viman nagar': 'Pune',
  'wadgaon sheri': 'Pune',
  'yerawada': 'Pune',
  'dhanori': 'Pune',
  'akurdi': 'Pune',
  'ghorpadi': 'Pune',
  'wanowrie': 'Pune',
  'noida': 'Noida',
  'greater noida': 'Noida',
  'dadri': 'Noida',
  'amrapali leisure valley': 'Noida',
  'sector 62': 'Noida',
  'sector 18': 'Noida',
  'amrapali dream valley': 'Noida',
  'sector 62a': 'Noida',
  'ahmedabad': 'Ahmedabad',
  'gandhinagar': 'Ahmedabad',
  'ahmadabad': 'Ahmedabad',
  'bodakdev': 'Ahmedabad',
  'bopal': 'Ahmedabad',
  'paldi': 'Ahmedabad',
  'maninagar': 'Ahmedabad',
  'nikol': 'Ahmedabad',
  'kolkata': 'Kolkata',
  'howrah': 'Kolkata',
  'tangra': 'Kolkata',
  'lucknow': 'Lucknow',
  'gurgaon': 'Gurgaon',
  'gurugram': 'Gurgaon',
  'sector 54': 'Gurgaon',
  'bhubaneswar': 'Bhubaneswar',
  'khordha': 'Bhubaneswar',
  'karimganj': 'Bhubaneswar',
  'jajapur': 'Bhubaneswar',
  'jajpur': 'Bhubaneswar',
  'bargarh': 'Bhubaneswar',
  'bhubaneshwar': 'Bhubaneswar',
  'nayapalli': 'Bhubaneswar',
  'surat': 'Surat',
  'athwa': 'Surat',
  'indore': 'Indore',
  'jaipur': 'Jaipur',
  'visakhapatnam': 'Visakhapatnam',
  'vijayawada': 'Vijayawada',
  'guntur': 'Guntur',
  'thiruvananthapuram': 'Thiruvananthapuram',
  'guwahati': 'Guwahati',
  'vadodara': 'Vadodara',
  'ludhiana': 'Ludhiana',
  'rajkot': 'Rajkot',
  'bhakti nagar': 'Rajkot',
  'nashik': 'Nashik',
  'faridabad': 'Faridabad',
  'mangalore': 'Mangaluru',
  'mangaluru': 'Mangaluru',
  'ghaziabad': 'Ghaziabad',
  'pratap vihar': 'Ghaziabad',
  'warangal': 'Warangal',
  'edappal': 'Kochi',
  'ernakulam': 'Kochi',
  'kochi': 'Kochi',
  'kanayannur': 'Kochi',
  'elamakkara': 'Kochi',
  'coimbatore': 'Coimbatore',
  'saravanampatti': 'Coimbatore',
  'mysuru': 'Mysore',
  'mysore': 'Mysore',
  'nagpur': 'Nagpur',
  'panaji': 'Goa',
  'old goa': 'Goa',
  'mohali': 'Mohali',
  'sahibzada ajit singh nagar': 'Mohali',
  'chandigarh': 'Chandigarh',
  'patna': 'Patna',
  'dehradun': 'Dehradun',
  'thrissur': 'Thrissur',
  'hubballi': 'Hubballi',
  'salem': 'Salem',
  'chhatrapati sambhajinagar': 'Sambhaji Nagar',
  'aurangabad': 'Sambhaji Nagar',
  'sambhaji nagar': 'Sambhaji Nagar',
  'belgaum': 'Belgaum',
  'belagavi': 'Belgaum',
  'kakinada': 'Kakinada',
  'bhopal': 'Bhopal',
  'kolhapur': 'Kolhapur',
  'kozhikode': 'Kozhikode',
  'madurai': 'Madurai',
  'kanpur': 'Kanpur',
  'tiruchirappalli': 'Tiruchirappalli',
  'kota': 'Kota',
  'tiruppur': 'Tiruppur',
  'tirupati': 'Tirupati',
  'rajahmundry': 'Rajahmundry',
  'rajamahendravaram': 'Rajahmundry',
  'udaipur': 'Udaipur',
  'sangli': 'Sangli',
  'karimnagar': 'KarimNagar',
  'bellari': 'Ballari',
  'ballari': 'Ballari',
  'hosur': 'Hosur',
  'atal nagar-nava raipur': 'Raipur',
  'raipur': 'Raipur',
  'kondapur': 'Hyderabad',
  'nallagandla': 'Hyderabad',
  'adai': 'Mumbai',
  'badlapur': 'Mumbai',
  'nilaje': 'Mumbai',
  'kelambakkam': 'Chennai',
  'guduvancheri': 'Chennai',
  'new town': 'Kolkata',
  'cuttack': 'Bhubaneswar',
  'kommaghatta': 'Bengaluru',
  'kazhakkoottam': 'Thiruvananthapuram',
  'madgaon': 'Goa',
};

export const TSC_CITIES = [
  'Bengaluru', 'Hyderabad', 'Mumbai', 'Rest', 'Chennai', 'Delhi',
  'Pune', 'Noida', 'Ahmedabad', 'Kolkata', 'Lucknow', 'Gurgaon',
  'Indore', 'Jaipur', 'Kochi', 'Coimbatore', 'Bhubaneswar', 'Surat',
  'Visakhapatnam', 'Vijayawada', 'Guwahati', 'Thiruvananthapuram',
  'Guntur', 'Vadodara', 'Faridabad', 'Ghaziabad', 'Ludhiana',
  'Mangaluru', 'Warangal', 'Rajkot', 'Nashik', 'Mysore', 'Goa',
  'Mohali', 'Nagpur', 'Dehradun', 'Patna', 'Thrissur', 'Kozhikode',
  'Madurai', 'Hubballi', 'Salem', 'Sambhaji Nagar', 'Kanpur',
  'Tiruchirappalli', 'Belgaum', 'Kakinada', 'Kolhapur', 'Bhopal',
  'Kota', 'Tiruppur', 'Tirupati', 'Rajahmundry', 'Udaipur', 'Sangli',
  'KarimNagar', 'Ballari', 'Hosur', 'Chandigarh', 'Raipur',
  'Unknown',
];

export function mapGoogleCity(googleCityName: string): string {
  if (!googleCityName || googleCityName.trim() === '') return 'Unknown';
  const lower = googleCityName.toLowerCase().trim();
  return GOOGLE_CITY_MAP[lower] || 'Rest';
}
