export const PRODUCT_TITLE_MAP: Record<string, string> = {
  "The Sleep Company Onyx Orthopedic Office Chair | Patented SmartGRID Technology | Adjustable Lumbar Support for Ergonomic Sitting Posture | Multiple": "Onyx Orthopedic Office Chair",
  "Elev8 Smart Recliner Bed with Italia Frame": "Recliner Bed",
  "The Sleep Company - Luxe Queen Size Mattress": "Smart Luxe Mattress",
  "The Sleep Company - Ortho Pro Mattress": "Smart Ortho Pro Mattress",
  "The Sleep Company - Ortho Queen Size Mattress": "Smart Ortho Mattress",
  "The Sleep Company - SmartGRID Luxe Mattress": "Smart Luxe Mattress",
  "The Sleep Company - SmartGRID Ortho Mattress": "Smart Ortho Mattress",
  "The Sleep Company Height Adjustable Desk | Dual Motor | Strong & Durable | Height Adjustable Table | 2 Years Warranty | Free Installation": "Height Adjustable Desk",
  "The Sleep Company Luxe Motorised Recliner Sofa - Revolving | Best Recliner Chair in India": "Recliner Sofa - Revolving",
  "The Sleep Company XGen Pro Gaming Chair | Gaming Comfort with Patented SmartGRID Technology | 4D Armrest | 2 Years Warranty": "XGen Pro Gaming Chair",
  "The Sleep Company - Luxe King Size Mattress": "Smart Luxe Mattress",
  "The Sleep Company - Ortho King Size Mattress": "Smart Ortho Mattress",
  "The Sleep Company - Ortho Pro King Size Mattress": "Smart Ortho Pro Mattress",
  "The Sleep Company - Ortho Pro Queen Size Mattress": "Smart Ortho Pro Mattress",
  "The Sleep Company - Luxe Hybrid King Size Mattress": "Smart Luxe Hybrid Mattress",
  "The Sleep Company - Luxe Hybrid Queen Size Mattress": "Smart Luxe Hybrid Mattress",
  "The Sleep Company - Ortho Diwan Mattress": "Smart Ortho Mattress",
  "The Sleep Company - Ortho Hybrid Pocketed Spring Mattress": "Smart Ortho Hybrid Mattress",
  "The Sleep Company - Ortho King Size 6 Inch Mattress": "Smart Ortho Mattress",
  "The Sleep Company - SmartGRID Ortho Hybrid Pocketed Spring Mattress": "Smart Ortho Hybrid Mattress",
  "The Sleep Company - Luxe Hybrid Mattress": "Smart Luxe Hybrid Mattress",
  "The Sleep Company Height Adjustable Desk | Dual Motor | 1200 MM | Height Adjustable Table | 2 Years Warranty | Free Installation": "Height Adjustable Desk",
  "Elev8 Smart Recliner Bed": "Recliner Bed",
  "Elev8 Smart Recliner Bed with Denver Leather Frame": "Recliner Bed",
  "Onyx Orthopedic Office Chair | Patented SmartGRID Technology | Adjustable Lumbar Support for Ergonomic Sitting Posture | Top Rated Office Chair": "Onyx Orthopedic Office Chair",
  "Stylux Ergonomic Office Chair | Adjustable Cushioned Ergonomic Lumbar Support for Work from Home & Office Chair": "Stylux Ergonomic Office Chair",
  "The Sleep Company Stylux Ergonomic Office Chair | Adjustable Cushioned Ergonomic Lumbar Support for Work from Home & Office Chair": "Stylux Ergonomic Office Chair",
  "The Sleep Company Ultron Premium Ergonomic Office Chair | Spine Protection | Chair with Footrest| Smart Adjustable Flexi Backrest": "Ultron Premium Ergonomic Office Chair",
  "The Sleep Company UNO Ergonomic Office Chair | Patented SmartGRID Technology | Adjustable Lumbar Support": "UNO Ergonomic Office Chair",
  "Motorised Recliner Sofa (Non-Revolving) - The Sleep Company | Best Recliner Chair in India": "Recliner Sofa - Non-Revolving",
  "Motorised Recliner Sofa (Non-Revolving) - The Sleep Company | Best Recliner Sofa in India": "Recliner Sofa - Non-Revolving",
  "Recliner Sofa (Revolving) - The Sleep Company | Best Recliner Chair in India": "Recliner Sofa - Revolving",
  "Recliner Sofa (Revolving) - The Sleep Company | Best Recliner Sofa in India": "Recliner Sofa - Revolving",
  "The Sleep Company Luxe Motorised Recliner Sofa - Non-Revolving | Best Recliner Chair in India": "Recliner Sofa - Non-Revolving",
  "The Sleep Company Luxe Motorised Recliner Sofa - Non-Revolving | Best Recliner Sofa in India": "Recliner Sofa - Non-Revolving",
  "The Sleep Company Luxe Motorised Recliner Sofa - Revolving | Best Recliner Sofa in India": "Recliner Sofa - Revolving",
  "The Sleep Company Luxe Pro Massager Recliner Sofa | Best Massage Chair in India": "Luxe Pro Massager Recliner Sofa",
  "SmartGRID Ortho SnowTec Cooling Technology - The Sleep Company": "Smart Ortho SnowTec Mattress",
  "The Sleep Company - Luxe Hybrid King Size Mattress with SnowTec Cooling Technology": "Smart Luxe SnowTec Mattress",
  "The Sleep Company - Luxe King Size Mattress with SnowTec Cooling Technology": "Smart Luxe SnowTec Mattress",
  "The Sleep Company - Luxe Queen Size Mattress with SnowTec Cooling Technology": "Smart Luxe SnowTec Mattress",
  "The Sleep Company - Ortho Hybrid Pocketed Spring King Size Mattress": "Smart Ortho Hybrid Mattress",
  "The Sleep Company - Ortho Hybrid Pocketed Spring Queen Size Mattress": "Smart Ortho Hybrid Mattress",
  "The Sleep Company - Ortho King Size 8 Inch Mattress": "Smart Ortho Mattress",
  "The Sleep Company - Ortho Pro Diwan Mattress": "Smart Ortho Pro Mattress",
  "The Sleep Company - Ortho Queen Size 6 Inch Mattress": "Smart Ortho Mattress",
  "The Sleep Company - Ortho Queen Size 8 Inch Mattress": "Smart Ortho Mattress",
  "The Sleep Company - Ortho Royale Mattress": "Smart Ortho Royale Mattress",
  "The Sleep Company Flex Ergonomic Office Chair | Adjustable Cushioned Ergonomic Lumbar Support for Work from Home & Office Chair": "Flex Ergonomic Office Chair",
  "2 Seater Recliner Sofa - Luxe Motorised Recliner Sofa Beige": "Luxe Motorised Recliner Sofa",
  "2 Seater Recliner Sofa - Luxe Motorised Recliner Sofa Grey": "Luxe Motorised Recliner Sofa",
  "2 Seater Recliner Sofa - Luxe Motorised Recliner Sofa Royal Blue": "Luxe Motorised Recliner Sofa",
  "AI Mattress: Buy SensAI Mattress Online in India King / 12 in / 78\" x 72\"": "SensAI Mattress",
  "AI Mattress: Buy SensAI Mattress Online in India Queen / 12 in / 78\" x 60\"": "SensAI Mattress",
  "All Weather Comforter": "All Weather Comforter",
  "All Weather Comforter Double": "All Weather Comforter",
  "Bamboo Mattress Protector": "Bamboo Mattress Protector",
  "Buy Cervical Pillow Online | Best Pillow for Neck Pain 1 Pillow": "Cervical Pillow",
  "Buy Cervical Pillow Online | Best Pillow for Neck Pain 2 Pillow": "Cervical Pillow",
  "Buy Festive Gifting Bundle Online | The Sleep Company": "Festive Gifting Bundle",
  "Buy Ortho Back Cushion for Office & Car - SmartGRID Support": "Ortho Back Cushion",
  "Buy Ortho Pro Back Cushion for Office & Car - SmartGRID Support": "Ortho Pro Back Cushion",
  "Buy Ortho Pro Seat Cushion for Office & Car - SmartGRID Comfort": "Ortho Pro Seat Cushion",
  "Buy Pregnancy Pillows Online | U-Shaped Cotton Maternity Pillow": "Pregnancy Pillow",
  "Buy Maroon Colors Pregnancy Pillow Online in India | The Sleep Company": "Pregnancy Pillow",
  "Buy Grey Colors Pregnancy Pillow Online in India | The Sleep Company Grey": "Pregnancy Pillow",
  "Buy Grey Colors Pregnancy Pillow Online in India | The Sleep Company Maroon": "Pregnancy Pillow",
  "Buy SensAI Sleep Analyzer Pillow Online – SmartGRID Technology & Sleep Score": "SensAI Mattress",
  "Shop SensAI Sleep Analyzer Online – Sleep Smarter Tonight": "SensAI Mattress",
  "Buy Smart Ergo Relief Pillow- 8 Shaped Ergonomic Design with Head Pocket 1 Pillow": "Smart Ergo Relief Pillow",
  "Buy Smart Ergo Relief Pillow- 8 Shaped Ergonomic Design with Head Pocket 2 Pillows": "Smart Ergo Relief Pillow",
  "Buy Smart Ergo Relief Pillow- 8 Shaped Ergonomic Design with Head Pocket 4 Pillows": "Smart Ergo Relief Pillow",
  "Smart Ergo Relief Pillow": "Smart Ergo Relief Pillow",
  "Buy Smart Neck Massager Pillow Online": "Smart Neck Massager Pillow",
  "Buy Smart Thin Pillow Online For Stomach & Back Sleepers Pack of 1": "Smart Thin Pillow",
  "Buy Smart Thin Pillow Online For Stomach & Back Sleepers Pack of 2": "Smart Thin Pillow",
  "Buy Smart Thin Pillow Online For Stomach & Back Sleepers Pack of 4": "Smart Thin Pillow",
  "Smart Adjustable Plush Pillow - Only @?999! Perfect for All Sleepers 1 Pillow": "Plush Pillow",
  "Smart Adjustable Plush Pillow - Only @?999! Perfect for All Sleepers 2 Pillow": "Plush Pillow",
  "Snowtec Adjustable Plush Pillow": "Plush Pillow",
  "SnowTec Adjustable Plush Pillow -Best Soft Pillow for Cooling Comfort 1 Pillow": "Plush Pillow",
  "SnowTec Adjustable Plush Pillow -Best Soft Pillow for Cooling Comfort 2 Pillow": "Plush Pillow",
  "SnowTec Adjustable Plush Pillow -Best Soft Pillow for Cooling Comfort 4 Pillow": "Plush Pillow",
  "Revlax Reversible Pillow - Dual-Sided Comfort with SmartGRID & Latex 1 Pillow": "Revlax Reversible Pillow",
  "Revlax Reversible Pillow - Dual-Sided Comfort with SmartGRID & Latex 2 Pillows": "Revlax Reversible Pillow",
  "Revlax Reversible Pillow - Dual-Sided Comfort with SmartGRID & Latex 4 Pillows": "Revlax Reversible Pillow",
  "Smart Revlax Pillow": "Smart Revlax Pillow",
  "Premium Sateen Bedsheets": "Premium Sateen Bedsheets",
  "Ortho Car Comfort Combo – Cushion Set for Back ,Neck & Seat Support": "Cushion",
  "Ortho Cushion Combo – Seat & Back Support for Office & Car": "Cushion",
  "Ortho Spine Protector Combo – Back Cushion & Car Neck Support": "Cushion",
  "Ortho Travel Support Combo – Seat Cushion & Neck Rest Cushion for Car": "Cushion",
  "The Sleep Company Ortho Pro Max Seat Cushion | Tailbone Pain Relief | Tailbone Cushion": "Seat Cushion",
  "The Sleep Company Ortho Pro Seat Cushion | Orthopedic Comfort for Long Sitting": "Seat Cushion",
  "The Sleep Company Wedge Cushion | Back Support | Reduces Back Pain": "Wedge Cushion",
  "The Sleep Company Gas Lift for XGen Chair Part Code XGCR 03": "Gas Lift for XGen Chair Part",
  "The Sleep Company - Smart Baby Mattress": "Smart Baby Mattress",
  "The Sleep Company Max Executive Office Chair | Ergonomic Full Body & Lumbar Support | Recline with Seat Slider | Postural Support": "Max Executive Office Chair",
  "The Sleep Company XGen Gaming Chair | Gaming Comfort with Patented SmartGRID Technology | 3D Armrest": "XGen Gaming Chair",
  "The Sleep Company Emilio Recliner Sofa | 2 Seater Sofa": "Elite Sofa",
  "The Sleep Company Emilio Recliner Sofa | 3 Seater Sofa": "Elite Sofa",
  "The Sleep Company Emperia Recliner Sofa | 3 Seater Sofa | LL": "Elite Sofa",
  "The Sleep Company Emperia Recliner Sofa | 3 Seater Sofa | RL": "Elite Sofa",
  "The Sleep Company Manila Recliner Sofa | 2 Seater Sofa": "Elite Sofa",
  "The Sleep Company Valencia Recliner Sofa | 2 Seater Sofa": "Elite Sofa",
  "The Sleep Company Valencia Recliner Sofa | 3 Seater Sofa": "Elite Sofa",
  "The Sleep Company Tranquo Massager Office Chair | Lumbar Massager which Reduces Back Pain for Work from Home & Office Chair": "Tranquo Massager Office Chair",
  "The Sleep Company Elite Premium Office Chair | Breathable Mesh & Lumbar Support for Work from Home & Office Chair": "Elite Premium Office Chair",
  "WaveX Foot Massager": "Foot Massager",
  "WaveX Foot Massager - 18 Customized Massage Grey": "Foot Massager",
  "WaveX Foot Massager - 18 Customized Massage Tan Leatherette": "Foot Massager",
  "WaveX Multipurpose Body Massager - Buy Body Massager Online": "Massager",
  "Glacier Thermo Fitted Sheet – Thermo Regulated Bedsheet Online King / 78\" x 72\" / Grey": "Thermo Fitted Sheet",
  "Glacier Thermo Fitted Sheet – Thermo Regulated Bedsheet Online King / 78\" x 72\" / White": "Thermo Fitted Sheet",
  "Glacier Thermo Fitted Sheet – Thermo Regulated Bedsheet Online King / 84\" x 72\" / Grey": "Thermo Fitted Sheet",
  "Sunrise Thermo Fitted Sheet - Buy Thermo Regulated Fitted Sheet Online King / 78\" x 72\" / White": "Thermo Fitted Sheet",
  "The Sleep Company - Ortho Grid Mattress": "Smart Ortho Grid Mattress",
  "Buy Smart Luxe Pro Latex Mattress – Luxury Comfort": "Smart Luxe Pro Mattress",
  "Buy Smart Luxe Pro Latex Mattress": "Smart Luxe Pro Mattress",
  "Smart luxe Pro Mattress Online - Latex + SmartGRID": "Smart Luxe Pro Mattress",
  "Smart luxe Pro Mattress Online": "Smart Luxe Pro Mattress",
};

export function getCleanProductName(rawTitle: string): string {
  if (PRODUCT_TITLE_MAP[rawTitle]) return PRODUCT_TITLE_MAP[rawTitle];
  
  // Try taking everything before the first slash (removes size/color variants)
  const baseSlash = rawTitle.split(/\s*\/\s*/)[0].trim();
  if (PRODUCT_TITLE_MAP[baseSlash]) return PRODUCT_TITLE_MAP[baseSlash];
  
  // Try matching if raw title starts with any of our known base keys
  // Sort by length descending to match the most specific prefix first
  const keys = Object.keys(PRODUCT_TITLE_MAP).sort((a, b) => b.length - a.length);
  for (const key of keys) {
    if (rawTitle.startsWith(key)) {
      return PRODUCT_TITLE_MAP[key];
    }
  }
  
  // Last resort: return the raw title truncated, flagged for review
  return rawTitle.length > 50 ? rawTitle.substring(0, 50) + '...' : rawTitle;
}
