export const PRODUCT_CATEGORY_MAP: Record<string, string> = {
  'Onyx Orthopedic Office Chair': 'Chair',
  'Stylux Ergonomic Office Chair': 'Chair',
  'XGen Pro Gaming Chair': 'Chair',
  'Ultron Premium Ergonomic Office Chair': 'Chair',
  'Tranquo Massager Office Chair': 'Chair',
  'UNO Ergonomic Office Chair': 'Chair',
  'Flex Ergonomic Office Chair': 'Chair',
  'Max Executive Office Chair': 'Chair',
  'XGen Gaming Chair': 'Chair',
  'Elite Premium Office Chair': 'Chair',
  'Height Adjustable Desk': 'Desk',
  'All Weather Comforter': 'Accessories',
  'Seat Cushion': 'Accessories',
  'Wedge Cushion': 'Accessories',
  'Foot Massager': 'Foot Massager',
  'Recliner Bed': 'Bed',
  'Elite Sofa': 'Elite',
  'Recliner Sofa - Revolving': 'Sofa',
  'Recliner Sofa - Non-Revolving': 'Sofa',
  'Luxe Pro Massager Recliner Sofa': 'Sofa',
  'Luxe Motorised Recliner Sofa': 'Sofa',

  // Newly requested explicit mattress/accessory products to ensure they appear
  'Smart Ortho Mattress': 'Mattress',
  'Smart Ortho Pro Mattress': 'Mattress',
  'Smart Ortho Hybrid Mattress': 'Mattress',
  'Smart Luxe Pro Mattress': 'Mattress',
  'Smart Ortho Grid Mattress': 'Mattress',
  'Smart Ortho SnowTec Mattress': 'Mattress',
  'Ortho Bundle': 'Mattress',
  'Plush Pillow': 'Mattress',
  'Smart Ortho Pro SnowTec Mattress': 'Mattress',
  'Premium Mattress': 'Mattress',
  'Smart Luxe Pro SnowTec Mattress': 'Mattress',
  'Festive Gifting Bundle': 'Mattress',
  'Ortho Back Cushion': 'Mattress',
  'Smart Luxe Hybrid Mattress': 'Mattress',
  'Grand Elite Mattress': 'Mattress',
  'Smart Luxe Royale Mattress': 'Mattress',
  'Luxe Bundle': 'Mattress',
  'Ortho Pro Back Cushion': 'Mattress',
  'Ortho Pro Seat Cushion': 'Mattress',
  'Smart Neck Massager Pillow': 'Mattress',
  'Pregnancy Pillow': 'Mattress',
  'Smart Thin Pillow': 'Mattress',
  'Bamboo Mattress Protector': 'Mattress',
  'Premium Sateen Bedsheets': 'Mattress',
  'Cervical Pillow': 'Mattress',
  'Smart Luxe SnowTec Mattress': 'Mattress',
  'Gas Lift for XGen Chair Part': 'Mattress',
  'Cushion': 'Mattress',
  'Bamboo Fitted Sheets with 2 Pillow Covers': 'Mattress',
  'Revlax Reversible Pillow': 'Mattress',
  'Smart Ortho Royale Mattress': 'Mattress',
  'SensAI Mattress': 'Mattress',
  'Smart Revlax Pillow': 'Mattress',
  'Smart Baby Mattress': 'Mattress',
  'Smart Ergo Relief Pillow': 'Mattress',
  'Smart Luxe Mattress': 'Mattress',
};

export function getCategoryForProduct(productName: string): string {
  return PRODUCT_CATEGORY_MAP[productName] || 'Mattress';
}
